/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as HomeRouteImport } from './routes/home'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as RoleRouteImport } from './routes/role'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupCustomerRouteImport } from './routes/setup.customer'
import { Route as SetupProviderRouteImport } from './routes/setup.provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupCustomerRoute = SetupCustomerRouteImport.update({
  id: '/setup/customer',
  path: '/setup/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupProviderRoute = SetupProviderRouteImport.update({
  id: '/setup/provider',
  path: '/setup/provider',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/complete': typeof CompleteRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/role': typeof RoleRoute
  '/signup': typeof SignupRoute
  '/setup/customer': typeof SetupCustomerRoute
  '/setup/provider': typeof SetupProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/complete': typeof CompleteRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/role': typeof RoleRoute
  '/signup': typeof SignupRoute
  '/setup/customer': typeof SetupCustomerRoute
  '/setup/provider': typeof SetupProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/complete': typeof CompleteRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/role': typeof RoleRoute
  '/signup': typeof SignupRoute
  '/setup/customer': typeof SetupCustomerRoute
  '/setup/provider': typeof SetupProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/complete'
    | '/home'
    | '/messages'
    | '/profile'
    | '/requests'
    | '/role'
    | '/signup'
    | '/setup/customer'
    | '/setup/provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/complete'
    | '/home'
    | '/messages'
    | '/profile'
    | '/requests'
    | '/role'
    | '/signup'
    | '/setup/customer'
    | '/setup/provider'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/complete'
    | '/home'
    | '/messages'
    | '/profile'
    | '/requests'
    | '/role'
    | '/signup'
    | '/setup/customer'
    | '/setup/provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  CompleteRoute: typeof CompleteRoute
  HomeRoute: typeof HomeRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  RequestsRoute: typeof RequestsRoute
  RoleRoute: typeof RoleRoute
  SignupRoute: typeof SignupRoute
  SetupCustomerRoute: typeof SetupCustomerRoute
  SetupProviderRoute: typeof SetupProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/customer': {
      id: '/setup/customer'
      path: '/setup/customer'
      fullPath: '/setup/customer'
      preLoaderRoute: typeof SetupCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/provider': {
      id: '/setup/provider'
      path: '/setup/provider'
      fullPath: '/setup/provider'
      preLoaderRoute: typeof SetupProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  CompleteRoute: CompleteRoute,
  HomeRoute: HomeRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  RequestsRoute: RequestsRoute,
  RoleRoute: RoleRoute,
  SignupRoute: SignupRoute,
  SetupCustomerRoute: SetupCustomerRoute,
  SetupProviderRoute: SetupProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
