/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as HomeRouteImport } from './routes/home'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as RoleRouteImport } from './routes/role'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProviderIndexRouteImport } from './routes/provider.index'
import { Route as ProviderAnalyticsRouteImport } from './routes/provider.analytics'
import { Route as ProviderAssistantRouteImport } from './routes/provider.assistant'
import { Route as ProviderCalendarRouteImport } from './routes/provider.calendar'
import { Route as ProviderEarningsRouteImport } from './routes/provider.earnings'
import { Route as ProviderJobsRouteImport } from './routes/provider.jobs'
import { Route as ProviderMessagesRouteImport } from './routes/provider.messages'
import { Route as ProviderProfileRouteImport } from './routes/provider.profile'
import { Route as ProviderSettingsRouteImport } from './routes/provider.settings'
import { Route as SetupCustomerRouteImport } from './routes/setup.customer'
import { Route as SetupProviderRouteImport } from './routes/setup.provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIndexRoute = ProviderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderAnalyticsRoute = ProviderAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderAssistantRoute = ProviderAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderCalendarRoute = ProviderCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderEarningsRoute = ProviderEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderJobsRoute = ProviderJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderMessagesRoute = ProviderMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderProfileRoute = ProviderProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderSettingsRoute = ProviderSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProviderRoute,
} as any)
const SetupCustomerRoute = SetupCustomerRouteImport.update({
  id: '/setup/customer',
  path: '/setup/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupProviderRoute = SetupProviderRouteImport.update({
  id: '/setup/provider',
  path: '/setup/provider',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/complete': typeof CompleteRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/provider': typeof ProviderRouteWithChildren
  '/requests': typeof RequestsRoute
  '/role': typeof RoleRoute
  '/signup': typeof SignupRoute
  '/provider/analytics': typeof ProviderAnalyticsRoute
  '/provider/assistant': typeof ProviderAssistantRoute
  '/provider/calendar': typeof ProviderCalendarRoute
  '/provider/earnings': typeof ProviderEarningsRoute
  '/provider/jobs': typeof ProviderJobsRoute
  '/provider/messages': typeof ProviderMessagesRoute
  '/provider/profile': typeof ProviderProfileRoute
  '/provider/settings': typeof ProviderSettingsRoute
  '/setup/customer': typeof SetupCustomerRoute
  '/setup/provider': typeof SetupProviderRoute
  '/provider/': typeof ProviderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/complete': typeof CompleteRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/role': typeof RoleRoute
  '/signup': typeof SignupRoute
  '/provider/analytics': typeof ProviderAnalyticsRoute
  '/provider/assistant': typeof ProviderAssistantRoute
  '/provider/calendar': typeof ProviderCalendarRoute
  '/provider/earnings': typeof ProviderEarningsRoute
  '/provider/jobs': typeof ProviderJobsRoute
  '/provider/messages': typeof ProviderMessagesRoute
  '/provider/profile': typeof ProviderProfileRoute
  '/provider/settings': typeof ProviderSettingsRoute
  '/setup/customer': typeof SetupCustomerRoute
  '/setup/provider': typeof SetupProviderRoute
  '/provider': typeof ProviderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/complete': typeof CompleteRoute
  '/home': typeof HomeRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/provider': typeof ProviderRouteWithChildren
  '/requests': typeof RequestsRoute
  '/role': typeof RoleRoute
  '/signup': typeof SignupRoute
  '/provider/analytics': typeof ProviderAnalyticsRoute
  '/provider/assistant': typeof ProviderAssistantRoute
  '/provider/calendar': typeof ProviderCalendarRoute
  '/provider/earnings': typeof ProviderEarningsRoute
  '/provider/jobs': typeof ProviderJobsRoute
  '/provider/messages': typeof ProviderMessagesRoute
  '/provider/profile': typeof ProviderProfileRoute
  '/provider/settings': typeof ProviderSettingsRoute
  '/setup/customer': typeof SetupCustomerRoute
  '/setup/provider': typeof SetupProviderRoute
  '/provider/': typeof ProviderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/complete'
    | '/home'
    | '/messages'
    | '/profile'
    | '/provider'
    | '/requests'
    | '/role'
    | '/signup'
    | '/provider/analytics'
    | '/provider/assistant'
    | '/provider/calendar'
    | '/provider/earnings'
    | '/provider/jobs'
    | '/provider/messages'
    | '/provider/profile'
    | '/provider/settings'
    | '/setup/customer'
    | '/setup/provider'
    | '/provider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/complete'
    | '/home'
    | '/messages'
    | '/profile'
    | '/requests'
    | '/role'
    | '/signup'
    | '/provider/analytics'
    | '/provider/assistant'
    | '/provider/calendar'
    | '/provider/earnings'
    | '/provider/jobs'
    | '/provider/messages'
    | '/provider/profile'
    | '/provider/settings'
    | '/setup/customer'
    | '/setup/provider'
    | '/provider'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/complete'
    | '/home'
    | '/messages'
    | '/profile'
    | '/provider'
    | '/requests'
    | '/role'
    | '/signup'
    | '/provider/analytics'
    | '/provider/assistant'
    | '/provider/calendar'
    | '/provider/earnings'
    | '/provider/jobs'
    | '/provider/messages'
    | '/provider/profile'
    | '/provider/settings'
    | '/setup/customer'
    | '/setup/provider'
    | '/provider/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  CompleteRoute: typeof CompleteRoute
  HomeRoute: typeof HomeRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  ProviderRoute: typeof ProviderRouteWithChildren
  RequestsRoute: typeof RequestsRoute
  RoleRoute: typeof RoleRoute
  SignupRoute: typeof SignupRoute
  SetupCustomerRoute: typeof SetupCustomerRoute
  SetupProviderRoute: typeof SetupProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/': {
      id: '/provider/'
      path: '/'
      fullPath: '/provider/'
      preLoaderRoute: typeof ProviderIndexRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/analytics': {
      id: '/provider/analytics'
      path: '/analytics'
      fullPath: '/provider/analytics'
      preLoaderRoute: typeof ProviderAnalyticsRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/assistant': {
      id: '/provider/assistant'
      path: '/assistant'
      fullPath: '/provider/assistant'
      preLoaderRoute: typeof ProviderAssistantRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/calendar': {
      id: '/provider/calendar'
      path: '/calendar'
      fullPath: '/provider/calendar'
      preLoaderRoute: typeof ProviderCalendarRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/earnings': {
      id: '/provider/earnings'
      path: '/earnings'
      fullPath: '/provider/earnings'
      preLoaderRoute: typeof ProviderEarningsRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/jobs': {
      id: '/provider/jobs'
      path: '/jobs'
      fullPath: '/provider/jobs'
      preLoaderRoute: typeof ProviderJobsRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/messages': {
      id: '/provider/messages'
      path: '/messages'
      fullPath: '/provider/messages'
      preLoaderRoute: typeof ProviderMessagesRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/profile': {
      id: '/provider/profile'
      path: '/profile'
      fullPath: '/provider/profile'
      preLoaderRoute: typeof ProviderProfileRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/settings': {
      id: '/provider/settings'
      path: '/settings'
      fullPath: '/provider/settings'
      preLoaderRoute: typeof ProviderSettingsRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/setup/customer': {
      id: '/setup/customer'
      path: '/setup/customer'
      fullPath: '/setup/customer'
      preLoaderRoute: typeof SetupCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/provider': {
      id: '/setup/provider'
      path: '/setup/provider'
      fullPath: '/setup/provider'
      preLoaderRoute: typeof SetupProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProviderRouteChildren {
  ProviderAnalyticsRoute: typeof ProviderAnalyticsRoute
  ProviderAssistantRoute: typeof ProviderAssistantRoute
  ProviderCalendarRoute: typeof ProviderCalendarRoute
  ProviderEarningsRoute: typeof ProviderEarningsRoute
  ProviderJobsRoute: typeof ProviderJobsRoute
  ProviderMessagesRoute: typeof ProviderMessagesRoute
  ProviderProfileRoute: typeof ProviderProfileRoute
  ProviderSettingsRoute: typeof ProviderSettingsRoute
  ProviderIndexRoute: typeof ProviderIndexRoute
}

const ProviderRouteChildren: ProviderRouteChildren = {
  ProviderAnalyticsRoute: ProviderAnalyticsRoute,
  ProviderAssistantRoute: ProviderAssistantRoute,
  ProviderCalendarRoute: ProviderCalendarRoute,
  ProviderEarningsRoute: ProviderEarningsRoute,
  ProviderJobsRoute: ProviderJobsRoute,
  ProviderMessagesRoute: ProviderMessagesRoute,
  ProviderProfileRoute: ProviderProfileRoute,
  ProviderSettingsRoute: ProviderSettingsRoute,
  ProviderIndexRoute: ProviderIndexRoute,
}

const ProviderRouteWithChildren = ProviderRoute._addFileChildren(
  ProviderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  CompleteRoute: CompleteRoute,
  HomeRoute: HomeRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  ProviderRoute: ProviderRouteWithChildren,
  RequestsRoute: RequestsRoute,
  RoleRoute: RoleRoute,
  SignupRoute: SignupRoute,
  SetupCustomerRoute: SetupCustomerRoute,
  SetupProviderRoute: SetupProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
